checks:
  php: true

filter:
  paths:
    - src/

build:
  image: default-bionic

  environment:
    php:
      version: 8.2
      ini:
        xdebug.mode: coverage

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    phpunit:
      services:
        mongo-db:
          image: mongo:4.0

          ports:
            - 27017

      dependencies:
        override:
          - yes "" | pecl install mongodb-1.20.1
          - composer self-update
          - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      tests:
        override:
          - command: ./vendor/bin/phpunit
